/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPickerField: typeof import('./src/components/utils/ColorPickerField.vue')['default']
    ConnectionManager: typeof import('./src/components/utils/ConnectionManager.vue')['default']
    DataPlayer: typeof import('./src/components/widgets/DataPlayer.vue')['default']
    DataRecorder: typeof import('./src/components/widgets/DataRecorder.vue')['default']
    DeviceCard: typeof import('./src/components/utils/DeviceCard.vue')['default']
    DeviceManager: typeof import('./src/components/utils/DeviceManager.vue')['default']
    DevicesView: typeof import('./src/components/views/DevicesView.vue')['default']
    FloatingControls: typeof import('./src/components/widgets/FloatingControls.vue')['default']
    MavlinkSettings: typeof import('./src/components/utils/MavlinkSettings.vue')['default']
    MultiView: typeof import('./src/components/views/MultiView.vue')['default']
    NotificationButton: typeof import('./src/components/utils/NotificationButton.vue')['default']
    NotificationMenu: typeof import('./src/components/utils/NotificationMenu.vue')['default']
    Ping1D: typeof import('./src/components/widgets/sonar1d/Ping1D.vue')['default']
    Ping1DLoader: typeof import('./src/components/widgets/sonar1d/Ping1DLoader.vue')['default']
    Ping1DSettings: typeof import('./src/components/widgets/sonar1d/Ping1DSettings.vue')['default']
    Ping360: typeof import('./src/components/widgets/sonar360/Ping360.vue')['default']
    Ping360Loader: typeof import('./src/components/widgets/sonar360/Ping360Loader.vue')['default']
    Ping360Settings: typeof import('./src/components/widgets/sonar360/Ping360Settings.vue')['default']
    ReplayView: typeof import('./src/components/views/ReplayView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerConnection: typeof import('./src/components/utils/ServerConnection.vue')['default']
    SettingsView: typeof import('./src/components/views/SettingsView.vue')['default']
    Sonar360Mask: typeof import('./src/components/widgets/sonar360/Sonar360Mask.vue')['default']
    Sonar360Shader: typeof import('./src/components/widgets/sonar360/Sonar360Shader.vue')['default']
    SonarColorOptions: typeof import('./src/components/widgets/SonarColorOptions.vue')['default']
    SplashScreen: typeof import('./src/components/utils/SplashScreen.vue')['default']
    StatisticsView: typeof import('./src/components/views/StatisticsView.vue')['default']
    VisualSettings: typeof import('./src/components/utils/VisualSettings.vue')['default']
    WaterfallMask: typeof import('./src/components/widgets/sonar1d/WaterfallMask.vue')['default']
    WaterfallShader: typeof import('./src/components/widgets/sonar1d/WaterfallShader.vue')['default']
    WebsocketAnalysisView: typeof import('./src/components/views/WebsocketAnalysisView.vue')['default']
    WebsocketClient: typeof import('./src/components/widgets/WebsocketClient.vue')['default']
  }
}
